name: Spell Checker
description: Check spelling in specified file
author: https://github.com/itsthecheat
requirements: []
configuration:
  properties:
    pattern:
      type: string
  additionalProperties: false