#!/bin/bash

set -euo pipefail

PATTERN="$BUILDKITE_PLUGIN_SPELL_CHECKER_PATTERN"

echo "Checking the spelling..."

WORDS=$(docker run --rm -ti -v $(pwd):/workdir tmaier/markdown-spellcheck:latest --report "$PATTERN")

echo "${WORDS} in files matching ${PATTERN}"

buildkite-agent annotate "${WORDS} in files matching ${PATTERN}"